"""Create tables

Revision ID: 6ba5fe2fd37e
Revises: 
Create Date: 2024-03-31 23:30:50.171075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba5fe2fd37e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('bus_number', sa.String(), nullable=True),
                    sa.Column('capacity', sa.Integer(), nullable=True),
                    sa.Column('route', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_buses_bus_number'),
                    'buses', ['bus_number'], unique=True)
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=True)
    op.create_table('routes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.Column('destination', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=True)
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('password_hash', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.create_table('prices',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('route_id', sa.UUID(), nullable=True),
                    sa.Column('bus_type', sa.String(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=True)
    op.create_table('reservations',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('passenger_name', sa.String(), nullable=True),
                    sa.Column('seat_number', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('bus_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_reservations_id'),
                    'reservations', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_bus_number'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
